<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('events')->insert([
            [
                'title' => 'Laravel 11: Kupas Tuntas Fitur Terbaru',
                'slug' => 'laravel-11-kupas-tuntas-fitur-terbaru',
                'description' => 'Bergabunglah bersama kami untuk mendalami fitur-fitur terbaru dan paling menarik di Laravel 11. Sesi ini akan mencakup pembahasan mendalam tentang Reverb, routing baru, dan peningkatan performa.',
                'speaker_name' => 'Budi Dharmawan',
                'speaker_title' => 'Senior Backend Developer di TechCorp',
                'speaker_image' => 'https://i.pravatar.cc/150?u=budi-dharmawan',
                'event_date' => Carbon::now()->addDays(30),
                'status' => 'upcoming',
                'registration_link' => 'https://example.com/register/laravel-11',
                'video_recording_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'React Native vs Flutter: Mana yang Terbaik untuk Proyek Anda?',
                'slug' => 'react-native-vs-flutter-proyek-anda',
                'description' => 'Sebuah debat dan diskusi panel tentang kelebihan dan kekurangan React Native dan Flutter. Dapatkan wawasan dari para ahli untuk membantu Anda memilih teknologi yang tepat untuk proyek mobile Anda berikutnya.',
                'speaker_name' => 'Citra Lestari',
                'speaker_title' => 'Mobile Development Lead di Inovasi Digital',
                'speaker_image' => 'https://i.pravatar.cc/150?u=citra-lestari',
                'event_date' => Carbon::now()->addDays(45),
                'status' => 'upcoming',
                'registration_link' => 'https://example.com/register/react-vs-flutter',
                'video_recording_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pengenalan DevOps untuk Pemula',
                'slug' => 'pengenalan-devops-untuk-pemula',
                'description' => 'Sesi ini telah berlalu. Kami membahas dasar-dasar DevOps, termasuk CI/CD, Infrastructure as Code, dan pentingnya kolaborasi antara tim pengembang dan operasional.',
                'speaker_name' => 'Agus Setiawan',
                'speaker_title' => 'DevOps Engineer di Cloudify',
                'speaker_image' => 'https://i.pravatar.cc/150?u=agus-setiawan',
                'event_date' => Carbon::now()->subDays(15),
                'status' => 'past',
                'registration_link' => null,
                'video_recording_url' => 'https://youtube.com/watch?v=example123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Membangun API Cepat dengan FastAPI',
                'slug' => 'membangun-api-cepat-dengan-fastapi',
                'description' => 'Pelajari cara membangun API yang sangat cepat dan efisien menggunakan FastAPI, framework Python modern. Workshop ini membahas validasi data, dokumentasi otomatis, dan fitur-fitur canggih lainnya.',
                'speaker_name' => 'Rina Hartono',
                'speaker_title' => 'Python Developer & AI Specialist',
                'speaker_image' => 'https://i.pravatar.cc/150?u=rina-hartono',
                'event_date' => Carbon::now()->subDays(60),
                'status' => 'past',
                'registration_link' => null,
                'video_recording_url' => 'https://youtube.com/watch?v=example456',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cybersecurity: Melindungi Aplikasi Web dari Serangan Umum',
                'slug' => 'cybersecurity-melindungi-aplikasi-web',
                'description' => 'Pahami ancaman keamanan siber yang paling umum seperti SQL Injection, XSS, dan CSRF. Pelajari praktik terbaik untuk mengamankan aplikasi web Anda dalam sesi yang informatif ini.',
                'speaker_name' => 'Doni Saputra',
                'speaker_title' => 'Ethical Hacker & Security Consultant',
                'speaker_image' => 'https://i.pravatar.cc/150?u=doni-saputra',
                'event_date' => Carbon::now()->addDays(60),
                'status' => 'upcoming',
                'registration_link' => 'https://example.com/register/cybersecurity-web',
                'video_recording_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Manajemen State di Vue 3: Pinia vs Vuex',
                'slug' => 'manajemen-state-vue-3-pinia-vs-vuex',
                'description' => 'Sesi perbandingan mendalam antara Pinia dan Vuex. Temukan mana yang lebih cocok untuk skala proyek Anda dan pelajari migrasi dari Vuex ke Pinia.',
                'speaker_name' => 'Santi Wulandari',
                'speaker_title' => 'Lead Frontend Engineer di KodeKreatif',
                'speaker_image' => 'https://i.pravatar.cc/150?u=santi-wulandari',
                'event_date' => Carbon::create(2025, 3, 12, 19, 0, 0),
                'status' => 'past',
                'registration_link' => null,
                'video_recording_url' => 'https://youtube.com/watch?v=example3',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'title' => 'Arsitektur Microservices: Kapan dan Bagaimana Memulainya?',
                'slug' => 'arsitektur-microservices-memulai',
                'description' => 'Pahami konsep dasar arsitektur microservices. Sesi ini akan membahas keuntungan, tantangan, dan kapan waktu yang tepat untuk mengadopsinya.',
                'speaker_name' => 'Joko Prasetyo',
                'speaker_title' => 'Solution Architect di ArchiTech',
                'speaker_image' => 'https://i.pravatar.cc/150?u=joko-prasetyo',
                'event_date' => Carbon::create(2025, 2, 18, 19, 0, 0),
                'status' => 'past',
                'registration_link' => null,
                'video_recording_url' => 'https://youtube.com/watch?v=example4',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'title' => 'Dasar-Dasar UI/UX untuk Developer',
                'slug' => 'dasar-ui-ux-untuk-developer',
                'description' => 'Tingkatkan kualitas aplikasi Anda dengan memahami prinsip-prinsip dasar UI/UX. Pelajari tentang hierarki visual, teori warna, dan desain yang berpusat pada pengguna.',
                'speaker_name' => 'Dewi Anggraini',
                'speaker_title' => 'Product Designer di PixelPerfect',
                'speaker_image' => 'https://i.pravatar.cc/150?u=dewi-anggraini',
                'event_date' => Carbon::create(2025, 9, 10, 19, 0, 0),
                'status' => 'upcoming',
                'registration_link' => 'https://example.com/register/ui-ux-basics',
                'video_recording_url' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'title' => 'Optimasi Performa Database PostgreSQL',
                'slug' => 'optimasi-performa-postgresql',
                'description' => 'Teknik dan praktik terbaik untuk meningkatkan kecepatan dan efisiensi query database PostgreSQL Anda, termasuk indexing, query analysis, dan konfigurasi server.',
                'speaker_name' => 'Hendra Gunawan',
                'speaker_title' => 'Database Administrator di DataNusa',
                'speaker_image' => 'https://i.pravatar.cc/150?u=hendra-gunawan',
                'event_date' => Carbon::create(2025, 1, 25, 19, 0, 0),
                'status' => 'past',
                'registration_link' => null,
                'video_recording_url' => 'https://youtube.com/watch?v=example5',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'title' => 'Mengenal Infrastructure as Code (IaC) dengan Terraform',
                'slug' => 'mengenal-iac-dengan-terraform',
                'description' => 'Workshop pengenalan tentang bagaimana mengelola dan menyediakan infrastruktur cloud secara otomatis menggunakan Terraform. Cocok untuk pemula.',
                'speaker_name' => 'Ivan Surya',
                'speaker_title' => 'Cloud Engineer',
                'speaker_image' => 'https://i.pravatar.cc/150?u=ivan-surya',
                'event_date' => Carbon::create(2024, 12, 5, 19, 0, 0),
                'status' => 'past',
                'registration_link' => null,
                'video_recording_url' => 'https://youtube.com/watch?v=example6',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'title' => 'Product Management 101: Dari Ide ke Peluncuran',
                'slug' => 'product-management-101',
                'description' => 'Pelajari siklus hidup pengembangan produk dari sudut pandang seorang Product Manager. Mulai dari validasi ide, riset pasar, hingga strategi peluncuran.',
                'speaker_name' => 'Fitriani Rahayu',
                'speaker_title' => 'Head of Product di SolusiCepat',
                'speaker_image' => 'https://i.pravatar.cc/150?u=fitriani-rahayu',
                'event_date' => Carbon::create(2025, 9, 28, 19, 0, 0),
                'status' => 'upcoming',
                'registration_link' => 'https://example.com/register/pm-101',
                'video_recording_url' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'title' => 'Membangun Aplikasi Real-Time dengan Socket.IO',
                'slug' => 'membangun-aplikasi-real-time-socket-io',
                'description' => 'Workshop teknis tentang cara membuat fitur interaktif real-time seperti notifikasi dan live chat menggunakan Node.js dan Socket.IO.',
                'speaker_name' => 'Fajar Nugroho',
                'speaker_title' => 'Full-Stack Developer',
                'speaker_image' => 'https://i.pravatar.cc/150?u=fajar-nugroho',
                'event_date' => Carbon::create(2024, 11, 20, 19, 0, 0),
                'status' => 'past',
                'registration_link' => null,
                'video_recording_url' => 'https://youtube.com/watch?v=example7',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'title' => 'Transformasi Digital untuk UKM: Studi Kasus & Strategi',
                'slug' => 'transformasi-digital-ukm',
                'description' => 'Sesi ini membahas bagaimana UKM dapat memanfaatkan teknologi digital dengan biaya efektif untuk meningkatkan penjualan dan efisiensi operasional.',
                'speaker_name' => 'Lina Marlina',
                'speaker_title' => 'Konsultan Bisnis Digital',
                'speaker_image' => 'https://i.pravatar.cc/150?u=lina-marlina',
                'event_date' => Carbon::create(2024, 10, 15, 19, 0, 0),
                'status' => 'past',
                'registration_link' => null,
                'video_recording_url' => 'https://youtube.com/watch?v=example8',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'title' => 'Pengenalan Machine Learning dengan Scikit-learn',
                'slug' => 'pengenalan-machine-learning-scikit-learn',
                'description' => 'Sesi untuk pemula yang ingin memahami konsep dasar Machine Learning dan mencoba implementasi pertamanya menggunakan library Scikit-learn di Python.',
                'speaker_name' => 'Eko Wijaya',
                'speaker_title' => 'Data Scientist',
                'speaker_image' => 'https://i.pravatar.cc/150?u=eko-wijaya',
                'event_date' => Carbon::create(2025, 10, 22, 19, 0, 0),
                'status' => 'upcoming',
                'registration_link' => 'https://example.com/register/ml-scikit',
                'video_recording_url' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'title' => 'Advanced Tailwind CSS: Membuat Desain Kustom',
                'slug' => 'advanced-tailwind-css-desain-kustom',
                'description' => 'Tingkatkan skill Tailwind CSS Anda. Pelajari cara mengkonfigurasi tema, membuat plugin kustom, dan mengoptimalkan file CSS untuk produksi.',
                'speaker_name' => 'Sari Putri',
                'speaker_title' => 'Frontend Architect',
                'speaker_image' => 'https://i.pravatar.cc/150?u=sari-putri',
                'event_date' => Carbon::create(2024, 9, 30, 19, 0, 0),
                'status' => 'past',
                'registration_link' => null,
                'video_recording_url' => 'https://youtube.com/watch?v=example9',
                'created_at' => now(), 'updated_at' => now(),
            ],
        ]);
    }
}